import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

const ContractView = () => {
  const [contractData, setContractData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Load contract from localStorage
    const savedContract = localStorage.getItem('generatedContract');
    if (savedContract) {
      try {
        const parsed = JSON.parse(savedContract);
        setContractData(parsed);
      } catch (error) {
        console.error('Error parsing contract data:', error);
      }
    }
    setLoading(false);
  }, []);

  const handleDownload = () => {
    if (!contractData) return;
    
    // Create a downloadable HTML file
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Contract - ${contractData.clientCompany}</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 40px; 
            line-height: 1.6; 
            color: #333;
        }
        .header { 
            text-align: center; 
            border-bottom: 2px solid #333; 
            padding-bottom: 20px; 
            margin-bottom: 30px; 
        }
        .company-name { 
            font-size: 24px; 
            font-weight: bold; 
            margin-bottom: 10px; 
            color: #2c3e50;
        }
        .contract-title { 
            font-size: 20px; 
            margin-bottom: 10px; 
            color: #34495e;
        }
        .date { 
            font-size: 14px; 
            color: #666; 
            margin-bottom: 20px;
        }
        .recipient { 
            margin-bottom: 20px; 
        }
        .section { 
            margin-bottom: 25px; 
        }
        .section-title { 
            font-size: 18px; 
            font-weight: bold; 
            color: #2c3e50; 
            border-bottom: 1px solid #bdc3c7; 
            padding-bottom: 5px; 
            margin-bottom: 15px; 
        }
        .content { 
            line-height: 1.8; 
        }
        pre { 
            white-space: pre-wrap; 
            font-family: inherit; 
            margin: 0;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 12px;
            color: #7f8c8d;
            border-top: 1px solid #bdc3c7;
            padding-top: 20px;
        }
        .signature-section { 
            margin-top: 50px; 
            padding-top: 30px; 
            border-top: 1px solid #ddd; 
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">PROPOSIFYAI SOLUTIONS</div>
        <div class="contract-title">SERVICE AGREEMENT CONTRACT</div>
        <div class="date">Date: ${new Date().toLocaleDateString()}</div>
    </div>
    
    <div class="recipient">
        <strong>Contract Between:</strong><br>
        <strong>Service Provider:</strong> ProposifyAI Solutions<br>
        <strong>Client:</strong> ${contractData.clientName}<br>
        <strong>Company:</strong> ${contractData.clientCompany}<br>
        <strong>Project:</strong> ${contractData.projectName}
    </div>

    <div class="content">
        ${contractData.content.replace(/\n/g, '<br>')}
    </div>

    <div class="signature-section">
        <p><strong>AGREEMENT:</strong></p>
        <p>By signing this contract, both parties agree to the terms and conditions outlined above.</p>
        <br><br>
        <p><strong>SERVICE PROVIDER:</strong></p>
        <p><strong>Company:</strong> ProposifyAI Solutions</p>
        <p><strong>Signature:</strong> ___________________________ &nbsp;&nbsp;&nbsp; <strong>Date:</strong> _______________</p>
        <br><br>
        <p><strong>CLIENT:</strong></p>
        <p><strong>Name:</strong> ${contractData.clientName}</p>
        <p><strong>Company:</strong> ${contractData.clientCompany}</p>
        <p><strong>Signature:</strong> ___________________________ &nbsp;&nbsp;&nbsp; <strong>Date:</strong> _______________</p>
        <br>
        <p><strong>Contract Generated:</strong> ${new Date(contractData.timestamp).toLocaleDateString()}</p>
    </div>

    <div class="footer">
        <p><strong>Generated by ProposifyAI</strong></p>
        <p>Professional Contract Generator</p>
        <p>Generated on ${new Date(contractData.timestamp).toLocaleDateString()}</p>
    </div>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `contract-${contractData.clientCompany.replace(/\s+/g, '-').toLowerCase()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600 mx-auto"></div>
          <p className="mt-2 text-gray-600">Loading contract...</p>
        </div>
      </div>
    );
  }

  if (!contractData) {
    return (
      <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">No Contract Found</h2>
          <p className="text-gray-600 mb-6">
            It looks like you haven't generated a contract yet.
          </p>
          <Link
            to="/project-form"
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            Generate New Contract
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-gray-900">Contract Viewer</h2>
        <div className="flex gap-4">
          <button
            onClick={handleDownload}
            className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-green-500"
          >
            Download HTML
          </button>
          <Link
            to="/project-form"
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            Generate New
          </Link>
        </div>
      </div>

      {/* Contract Header */}
      <div className="bg-gray-50 border rounded-lg p-6 mb-6">
        <h3 className="text-lg font-semibold mb-2">Contract Details</h3>
        <div className="grid grid-cols-2 gap-4 text-sm">
          <div><strong>Client:</strong> {contractData.clientName}</div>
          <div><strong>Company:</strong> {contractData.clientCompany}</div>
          <div><strong>Project:</strong> {contractData.projectName}</div>
          <div><strong>Generated:</strong> {new Date(contractData.timestamp).toLocaleDateString()}</div>
        </div>
      </div>

      {/* Contract Content */}
      <div className="border rounded-lg p-8 bg-gray-50">
        <div className="bg-white rounded-lg p-8 shadow-sm">
          <pre className="whitespace-pre-wrap text-sm text-gray-800 font-sans leading-relaxed">
            {contractData.content}
          </pre>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="mt-8 flex justify-center gap-4">
        <button
          onClick={handleDownload}
          className="bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-6 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500"
        >
          📄 Download Contract (HTML)
        </button>
        <Link
          to="/dashboard"
          className="bg-gray-600 hover:bg-gray-700 text-white font-bold py-3 px-6 rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-500"
        >
          ← Back to Dashboard
        </Link>
      </div>

      {/* Info Footer */}
      <div className="mt-8 text-center text-sm text-gray-500 border-t pt-6">
        <p>
          <strong>Generated by ProposifyAI</strong> - Professional Contract Generator
        </p>
        <p>
          Generated on {new Date(contractData.timestamp).toLocaleDateString()} at {new Date(contractData.timestamp).toLocaleTimeString()}
        </p>
      </div>
    </div>
  );
};

export default ContractView;
