import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

const OfferLetterView = () => {
  const [offerLetterData, setOfferLetterData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Load offer letter from localStorage
    const savedOfferLetter = localStorage.getItem('generatedOfferLetter');
    if (savedOfferLetter) {
      try {
        const parsed = JSON.parse(savedOfferLetter);
        setOfferLetterData(parsed);
      } catch (error) {
        console.error('Error parsing offer letter data:', error);
      }
    }
    setLoading(false);
  }, []);

  const handleDownload = () => {
    if (!offerLetterData) return;
    
    // Create a downloadable HTML file
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Offer Letter - ${offerLetterData.candidateName}</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 40px; 
            line-height: 1.6; 
            color: #333;
        }
        .header { 
            text-align: center; 
            border-bottom: 2px solid #333; 
            padding-bottom: 20px; 
            margin-bottom: 30px; 
        }
        .company-name { 
            font-size: 24px; 
            font-weight: bold; 
            margin-bottom: 10px; 
            color: #2c3e50;
        }
        .date { 
            font-size: 14px; 
            color: #666; 
            margin-bottom: 20px;
        }
        .recipient { 
            margin-bottom: 20px; 
        }
        .section { 
            margin-bottom: 25px; 
        }
        .section-title { 
            font-size: 18px; 
            font-weight: bold; 
            color: #2c3e50; 
            border-bottom: 1px solid #bdc3c7; 
            padding-bottom: 5px; 
            margin-bottom: 15px; 
        }
        .content { 
            line-height: 1.8; 
        }
        pre { 
            white-space: pre-wrap; 
            font-family: inherit; 
            margin: 0;
        }
        .signature-section { 
            margin-top: 50px; 
            padding-top: 30px; 
            border-top: 1px solid #ddd; 
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 12px;
            color: #7f8c8d;
            border-top: 1px solid #bdc3c7;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">${offerLetterData.companyName.toUpperCase()}</div>
        <div class="date">Date: ${new Date().toLocaleDateString()}</div>
    </div>
    
    <div class="recipient">
        <strong>To:</strong> ${offerLetterData.candidateName}<br>
        <strong>From:</strong> ${offerLetterData.companyName}
    </div>

    <div class="content">
        ${offerLetterData.content.replace(/\n/g, '<br>')}
    </div>

    <div class="signature-section">
        <p><strong>ACCEPTANCE:</strong></p>
        <p>I, ${offerLetterData.candidateName}, hereby accept the terms and conditions of employment as outlined in this offer letter.</p>
        <br><br>
        <p><strong>Signature:</strong> ___________________________ &nbsp;&nbsp;&nbsp; <strong>Date:</strong> _______________</p>
        <p><strong>Name:</strong> ${offerLetterData.candidateName}</p>
    </div>

    <div class="footer">
        <p><strong>Generated by ProposifyAI</strong></p>
        <p>Professional Offer Letter Generator</p>
        <p>Generated on ${new Date(offerLetterData.timestamp).toLocaleDateString()}</p>
    </div>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `offer-letter-${offerLetterData.candidateName.replace(/\s+/g, '-').toLowerCase()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600 mx-auto"></div>
          <p className="mt-2 text-gray-600">Loading offer letter...</p>
        </div>
      </div>
    );
  }

  if (!offerLetterData) {
    return (
      <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">No Offer Letter Found</h2>
          <p className="text-gray-600 mb-6">
            It looks like you haven't generated an offer letter yet.
          </p>
          <Link
            to="/offer-letter-form"
            className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-purple-500"
          >
            Generate New Offer Letter
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-gray-900">Offer Letter Viewer</h2>
        <div className="flex gap-4">
          <button
            onClick={handleDownload}
            className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-green-500"
          >
            Download HTML
          </button>
          <Link
            to="/offer-letter-form"
            className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-purple-500"
          >
            Generate New
          </Link>
        </div>
      </div>

      {/* Offer Letter Content */}
      <div className="border rounded-lg p-8 bg-gray-50">
        <div className="bg-white rounded-lg p-8 shadow-sm">
          <pre className="whitespace-pre-wrap text-sm text-gray-800 font-sans leading-relaxed">
            {offerLetterData.content}
          </pre>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="mt-8 flex justify-center gap-4">
        <button
          onClick={handleDownload}
          className="bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-6 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500"
        >
          📄 Download Offer Letter (HTML)
        </button>
        <Link
          to="/dashboard"
          className="bg-gray-600 hover:bg-gray-700 text-white font-bold py-3 px-6 rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-500"
        >
          ← Back to Dashboard
        </Link>
      </div>

      {/* Info Footer */}
      <div className="mt-8 text-center text-sm text-gray-500 border-t pt-6">
        <p>
          <strong>Generated by ProposifyAI</strong> - Professional Offer Letter Generator
        </p>
        <p>
          Generated on {new Date(offerLetterData.timestamp).toLocaleDateString()} at {new Date(offerLetterData.timestamp).toLocaleTimeString()}
        </p>
      </div>
    </div>
  );
};

export default OfferLetterView;
