import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

const ResumeView = () => {
  const [resumeData, setResumeData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Load resume from localStorage
    const savedResume = localStorage.getItem('generatedResume');
    if (savedResume) {
      try {
        const parsed = JSON.parse(savedResume);
        setResumeData(parsed);
      } catch (error) {
        console.error('Error parsing resume data:', error);
      }
    }
    setLoading(false);
  }, []);

  const handleDownload = () => {
    if (!resumeData) return;
    
    // Create a downloadable HTML file
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Resume - ${resumeData.candidateName}</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 40px; 
            line-height: 1.6; 
            color: #333;
        }
        .header { 
            text-align: center; 
            border-bottom: 2px solid #333; 
            padding-bottom: 20px; 
            margin-bottom: 30px; 
        }
        .name { 
            font-size: 28px; 
            font-weight: bold; 
            margin-bottom: 10px; 
            color: #2c3e50;
        }
        .contact-info { 
            font-size: 14px; 
            color: #666; 
            margin-bottom: 10px;
        }
        .section { 
            margin-bottom: 25px; 
        }
        .section-title { 
            font-size: 18px; 
            font-weight: bold; 
            color: #2c3e50; 
            border-bottom: 1px solid #bdc3c7; 
            padding-bottom: 5px; 
            margin-bottom: 15px; 
        }
        .content { 
            line-height: 1.8; 
        }
        .skills-list {
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
        }
        .skill-tag {
            background: #ecf0f1;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 12px;
        }
        pre { 
            white-space: pre-wrap; 
            font-family: inherit; 
            margin: 0;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 12px;
            color: #7f8c8d;
            border-top: 1px solid #bdc3c7;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="name">${resumeData.candidateName}</div>
        <div class="contact-info">Generated by ProposifyAI on ${new Date(resumeData.timestamp).toLocaleDateString()}</div>
    </div>
    
    <div class="content">
        ${resumeData.content.replace(/\n/g, '<br>')}
    </div>

    <div class="footer">
        <p><strong>Generated by ProposifyAI</strong></p>
        <p>Professional Resume Generator</p>
        <p>Generated on ${new Date(resumeData.timestamp).toLocaleDateString()}</p>
    </div>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `resume-${resumeData.candidateName.replace(/\s+/g, '-').toLowerCase()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600 mx-auto"></div>
          <p className="mt-2 text-gray-600">Loading resume...</p>
        </div>
      </div>
    );
  }

  if (!resumeData) {
    return (
      <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">No Resume Found</h2>
          <p className="text-gray-600 mb-6">
            It looks like you haven't generated a resume yet.
          </p>
          <Link
            to="/resume-form"
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            Generate New Resume
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-gray-900">Resume Viewer</h2>
        <div className="flex gap-4">
          <button
            onClick={handleDownload}
            className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-green-500"
          >
            Download HTML
          </button>
          <Link
            to="/resume-form"
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            Generate New
          </Link>
        </div>
      </div>

      {/* Resume Content */}
      <div className="border rounded-lg p-8 bg-gray-50">
        <div className="bg-white rounded-lg p-8 shadow-sm">
          <pre className="whitespace-pre-wrap text-sm text-gray-800 font-sans leading-relaxed">
            {resumeData.content}
          </pre>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="mt-8 flex justify-center gap-4">
        <button
          onClick={handleDownload}
          className="bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-6 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500"
        >
          📄 Download Resume (HTML)
        </button>
        <Link
          to="/dashboard"
          className="bg-gray-600 hover:bg-gray-700 text-white font-bold py-3 px-6 rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-500"
        >
          ← Back to Dashboard
        </Link>
      </div>

      {/* Info Footer */}
      <div className="mt-8 text-center text-sm text-gray-500 border-t pt-6">
        <p>
          <strong>Generated by ProposifyAI</strong> - Professional Resume Generator
        </p>
        <p>
          Generated on {new Date(resumeData.timestamp).toLocaleDateString()} at {new Date(resumeData.timestamp).toLocaleTimeString()}
        </p>
      </div>
    </div>
  );
};

export default ResumeView;
